### PR TITLE
Simplify RPM packaging, fix prerelease version handling

### LINKED ISSUE #162: CI: package generation mishandles prerelease strings
tenstorrent-dkms_2.5.0_all.deb may contain 2.5.0-rc1, but this is not reflected in the filename.
/usr/src/ has tenstorrent-2.5.0 not tenstorrent-2.5.0-rc1 - possible risk of conflict when upgrading from -rc1 to the final release.

### LINKED ISSUE #214: [Bug]: ppa installs -rc1 when final is avalaible
On Ubuntu 22.04 with the tt ppa enabled and the `tenstorrent-dkms` package is installed.

The version `2.7.0-rc1` is installed but the repo makes `2.7.0` available, which I assume should take precedence.

The Debian policy manual indicates a prerelease version should be separated by a tilde so it sorts with lower precedence than the final:

https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
> One common use of ~ is for upstream pre-releases. For example, 1.0~beta1~svn1245 sorts earlier than 1.0~beta1, which sorts earlier than 1.0.

So the `2.7.0-rc1` package should probably be called `2.7.0~rc1`.

```
ttuser@tt-quietbox:~$ apt policy tenstorrent-dkms
tenstorrent-dkms:
  Installed: 2.7.0-rc1
  Candidate: 2.7.0-rc1
  Version table:
 *** 2.7.0-rc1 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
        100 /var/lib/dpkg/status
     2.7.0 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
     2.6.0-rc1 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
     2.6.0 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
     2.5.0 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
     2.4.1 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
     2.4.0 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
     2.3.0-1 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
     2.2.0-1 500
        500 https://ppa.tenstorrent.com/ubuntu jammy/main amd64 Packages
        500 https://ppa.tenstorrent.com/ubuntu jammy/main all Packages
```

### PR DESCRIPTION
**Pull request by joelsmithTT**
Closes #162
Closes #214

Prerelease versions like `2.5.0-rc1` were truncated to `2.5.0` in RPM filenames and install paths, risking conflicts when upgrading from prerelease to final release. The same problem affected deb packages, where `2.7.0-rc1` sorted higher than `2.7.0` in apt.

## Changes
Add `tools/build_rpms.sh` — a self-contained local build script (mirrors `build_debs.sh`) that:
- Reads version from `module.h` via `tools/current-version`
- Converts prerelease separator for RPM (`2.6.1-pre` to `2.6.1~pre`)
- Preserves full version in install path and filename
- Generates the spec file dynamically
- Installs udev rules into `/lib/udev/rules.d/`
- Runs DKMS removal only on full uninstall, not upgrade
- Shows a helpful message when the module isn't built for the running kernel

Simplify `.github/workflows/build-rpm.yml` from ~200 lines to ~40 by calling the script.

Remove the 3-container matrix build, non-functional GPG signing, and version inputs that are no longer needed.

Remove `tenstorrent-dkms.spec` (now generated by the build script).

Fix prerelease version sorting in `build_debs.sh` — convert hyphen to tilde (`2.7.0-rc1` becomes `2.7.0~rc1`) so apt correctly prefers the final release over the release candidate.

Fix whitespace matching in the dkms.conf version sanity check (`build_debs.sh` used literal `s` instead of `\s`).

## Testing
RPM built and installed on Rocky 10

### CODE REVIEW

File: tools/build_rpms.sh [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+mkdir -p "${RPMBUILD}"/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
+
+# Create source tarball
+# RPM expects the tarball to extract to a directory named ${MODULE_NAME}-${RPM_VERSION}
+SRC_STAGING="${BUILD_DIR}/${MODULE_NAME}-${RPM_VERSION}"
+mkdir -p "${SRC_STAGING}"
+
+echo "Creating source tarball..."
+cd "${PROJECT_ROOT}"
+tar -c --exclude-from=tools/exclude-from-release -f - . | tar -C "${SRC_STAGING}" -xf -
```
Comment (alewycky-tenstorrent) [inline tools/build_rpms.sh]: Combine -c & -f into -cf.

**Review by alewycky-tenstorrent — APPROVED** [review]
